### ISSUE TITLE
Version 0.3.0 Does Not Reflect Master

### ISSUE THREAD

**Issue by dchang-novotec** [jwt/ruby-jwe#14]
I tried encrypting custom headers however i found that version 0.3.0 that I installed from rubygems.org does not reflect what is in master.

**Comment by aomega08** [comment]
Well, master is the branch with the latest changes, which may or may not have been released already.

I've done a series of style fixes since last release, and that's why 0.3.0 does not match what's in master, but it wasn't worth to make another release just for style...

Anyway, if you need to explore the source for that release, you can find it here: https://github.com/jwt/ruby-jwe/tree/6acb56b3d4ef7d963985b44c35538b4f94a5837f
